# Generated by Django 4.0.4 on 2022-04-24 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id_stud', models.BigAutoField(primary_key=True, serialize=False)),
                ('indeks', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(6), django.core.validators.MinLengthValidator(6)])),
                ('imie', models.CharField(max_length=80)),
                ('nazwisko', models.CharField(max_length=80)),
                ('pesel', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(11), django.core.validators.MinLengthValidator(11)])),
            ],
            options={
                'ordering': ['-id_stud'],
            },
        ),
    ]
