# Generated by Django 4.0.4 on 2022-04-24 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_student_indeks_alter_student_pesel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='indeks',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='pesel',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(99999999999), django.core.validators.MinValueValidator(10000000000)]),
        ),
    ]
