# Generated by Django 4.0.4 on 2022-04-25 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_student_indeks_alter_student_pesel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['id_stud']},
        ),
    ]
