# Generated by Django 4.0.4 on 2022-06-04 11:30

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_student_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pesel',
            field=models.CharField(max_length=11, unique=True, validators=[api.models.pesel_validator, django.core.validators.MinLengthValidator(11)]),
        ),
    ]
